#!/usr/bin/env sh

yabai -m config \
    mouse_follows_focus off \
    focus_follows_mouse on \
    window_origin_display default \
    window_placement second_child \
    window_topmost off \
    window_shadow off \
    window_opacity off \
    window_opacity_duration 0.0 \
    active_window_opacity 1.0 \
    normal_window_opacity 0.90 \
    window_border off \
    window_border_width 6 \
    active_window_border_color 0xff775759 \
    normal_window_border_color 0xff555555 \
    insert_feedback_color 0xffd75f5f \
    split_ratio 0.50 \
    split_type vertical \
    auto_balance off \
    mouse_modifier fn \
    mouse_action1 move \
    mouse_action2 resize \
    mouse_drop_action swap \
    top_padding 0 \
    bottom_padding 0 \
    external_bar all:0:27 \
    left_padding 0 \
    right_padding 0 \
    window_gap 06 \
    rule --add app="^System Preferences$" manage=off \
    rule --add app="^システム設定$" manage=off \
    layout bsp

yabai -m signal --add \
    event=window_moved action="sketchybar --trigger yabai_window_moved" \
    label=yabai_window_moved 
yabai -m signal --add \
    event=window_focused action="sketchybar --trigger yabai_window_focused" \
    label=yabai_window_focused

echo "yabai configuration loaded.."
